name: banderfront_ci

on: [push, pull_request]

jobs:
  build:
    name: bandersnatch CI python ${{ matrix.python-version }} on ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.12]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@master

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install latest pip + setuptools
      run: |
        python -m pip install --upgrade pip setuptools wheel

    - name: Install base pinned requirements
      run: |
        python -m pip install -r requirements.txt

    - name: Run Integration Test
      env:
        pythonioencoding: utf-8
      run: |
        python -m pip install .
        python ci.py
